name: outfit_consultant
description: Virtual outfit consultant with web search, catalog, and try-on.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.4
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  path_provider: ^2.1.4
  uuid: ^4.4.2
  transparent_image: ^2.0.1
  image: ^4.1.7
  url_launcher: ^6.3.0
  media_store_plus: ^0.1.3
  intl: ^0.20.0
  flutter_markdown: ^0.6.19
  share_plus: ^12.0.1
  google_fonts: ^6.1.0
  gal: ^2.3.0
  video_player_win: ^3.2.2
  video_player: ^2.10.1
  supabase_flutter: ^2.3.4
  

flutter:
  uses-material-design: true
  assets:
    - assets/mannequins/male.png
    - assets/mannequins/female.png
    - assets/translations/
    - assets/icon/
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/app_icon.png
  android_12:
    image: assets/icon/app_icon.png
    color: "#FFFFFF"

flutter_launcher_icons:
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 256
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

